[package]
name = "roc_server"
version = "0.1.0"
authors = ["roepfeli <85442544+roepfeli@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
signal-hook = "0.3.10"
regex = "1.5.4"